"""Run pipeline: Scout -> Plan -> (per instance) Generate -> Collect.

Each instance is generated by its own fresh, stateless agent session. The
orchestrator owns the container, stages the harness once, and persists every
artifact to the host as soon as it exists (crash-safe, resumable by re-run).
"""

from __future__ import annotations

import datetime as _dt
import json
import shlex
import shutil
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Optional

from .agents import AgentBackend
from .config import PAYLOAD_DIR, RunConfig
from .docker_env import Container
from .planner import PlannedInstance, Planner
from .prompting import PromptBuilder


@dataclass
class InstanceRecord:
    instance_id: str
    category: str
    target_file: str
    target_qualname: str
    status: str  # planned | generated | agent_failed | no_oracle
    note: str = ""
    started_at: str = ""
    finished_at: str = ""


@dataclass
class RunManifest:
    repo_key: str
    image: str
    agent: str
    model: str
    seed: int
    created_at: str
    instances: list[dict] = field(default_factory=list)

    def save(self, path: Path) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        with path.open("w", encoding="utf-8") as f:
            json.dump(asdict(self), f, indent=2)
            f.write("\n")


class Orchestrator:
    def __init__(self, config: RunConfig, backend: Optional[AgentBackend]):
        self.config = config
        self.backend = backend
        timestamp = _dt.datetime.now().strftime("%Y%m%d_%H%M%S")
        self.run_dir = config.run_dir(timestamp)
        self.instances_dir = self.run_dir / "instances"
        self.logs_dir = self.run_dir / "logs"
        self.manifest = RunManifest(
            repo_key=config.repo_key,
            image=config.image,
            agent=config.agent_name,
            model=config.model,
            seed=config.seed,
            created_at=timestamp,
        )

    # -- public entry points -------------------------------------------

    def run(self) -> Path:
        config = self.config
        self.run_dir.mkdir(parents=True, exist_ok=True)
        self._save_config()

        if config.plan_only and config.targets_json:
            targets = self._load_targets(config.targets_json)
            plan = self._plan(targets)
            self._save_plan(plan)
            print(f"plan-only: wrote plan for {len(plan)} instances to {self.run_dir}")
            return self.run_dir

        container = Container(config.image, workdir=config.workdir)
        try:
            print(f"[container] starting {config.image}")
            container.start()
            self._stage_harness(container)

            targets = self._scout(container)
            plan = self._plan(targets)
            self._save_plan(plan)
            if config.plan_only:
                print(f"plan-only: wrote plan for {len(plan)} instances")
                return self.run_dir

            self._write_host_scaffold()

            assert self.backend is not None
            print(f"[agent] preparing backend '{self.backend.name}'")
            self.backend.prepare(container)

            generated_ids: list[str] = []
            prompt_builder = PromptBuilder(config)
            for index, planned in enumerate(plan, start=1):
                print(
                    f"[{index}/{len(plan)}] {planned.instance_id} "
                    f"({planned.category} on {planned.target['qualname']})"
                )
                record = self._generate_one(
                    container, prompt_builder, planned, generated_ids
                )
                if record.status == "generated":
                    generated_ids.append(planned.instance_id)
                self.manifest.instances.append(asdict(record))
                self.manifest.save(self.run_dir / "manifest.json")
                print(f"    -> {record.status} {record.note}".rstrip())
            return self.run_dir
        finally:
            if config.keep_container:
                print(f"[container] kept alive: {container.name}")
            else:
                container.stop()

    # -- pipeline stages -------------------------------------------------

    def _stage_harness(self, container: Container) -> None:
        """Stage shared tracer/conftest + qa_pipeline.sh into the QA dir once."""
        qa_dir = self.config.container_qa_dir
        container.exec(f"mkdir -p '{qa_dir}/shared/files' /tmp/repogen")
        for name in ("trace_plugin.py", "conftest.py"):
            container.cp_to(
                PAYLOAD_DIR / "shared" / "files" / name,
                f"{qa_dir}/shared/files/{name}",
            )
        container.cp_to(PAYLOAD_DIR / "qa_pipeline.sh", f"{qa_dir}/qa_pipeline.sh")
        container.exec(f"chmod +x '{qa_dir}/qa_pipeline.sh'")

    def _write_host_scaffold(self) -> None:
        """Make instances/ a drop-in QA folder, runnable from host exactly like
        the original benchmark: shared/ tracer files, qa_pipeline.sh, and the
        two host runners (run_qa_fromhost.sh rendered with this repo's image)."""
        qa_root = self.instances_dir
        (qa_root / "shared" / "files").mkdir(parents=True, exist_ok=True)
        for name in ("trace_plugin.py", "conftest.py"):
            shutil.copy2(
                PAYLOAD_DIR / "shared" / "files" / name,
                qa_root / "shared" / "files" / name,
            )
        shutil.copy2(PAYLOAD_DIR / "qa_pipeline.sh", qa_root / "qa_pipeline.sh")
        shutil.copy2(
            PAYLOAD_DIR / "run_all_qa_fromhost.sh", qa_root / "run_all_qa_fromhost.sh"
        )
        runner = (
            (PAYLOAD_DIR / "run_qa_fromhost.sh.tpl")
            .read_text(encoding="utf-8")
            .replace("{{IMAGE}}", self.config.image)
            .replace("{{QA_DIR_NAME}}", self.config.qa_dir_name)
        )
        (qa_root / "run_qa_fromhost.sh").write_text(runner, encoding="utf-8")
        for script in ("qa_pipeline.sh", "run_qa_fromhost.sh", "run_all_qa_fromhost.sh"):
            (qa_root / script).chmod(0o755)
        print(f"[scaffold] host QA folder ready: {qa_root}")

    def _scout(self, container: Container) -> list[dict]:
        if self.config.targets_json:
            targets = self._load_targets(self.config.targets_json)
            print(f"[scout] loaded {len(targets)} targets from {self.config.targets_json}")
            return targets
        container.cp_to(PAYLOAD_DIR / "scout_targets.py", "/tmp/repogen/scout_targets.py")
        result = container.exec(
            f"python /tmp/repogen/scout_targets.py "
            f"--root {shlex.quote(self.config.workdir)} "
            f"--out /tmp/repogen/targets.json "
            f"--exclude-dir {shlex.quote(self.config.qa_dir_name)}",
            timeout_s=600,
        )
        if not result.ok:
            raise RuntimeError(f"scout failed: {result.stderr or result.stdout}")
        host_targets = self.run_dir / "targets.json"
        container.cp_from("/tmp/repogen/targets.json", host_targets)
        targets = self._load_targets(host_targets)
        print(f"[scout] mined {len(targets)} candidate targets")
        return targets

    def _plan(self, targets: list[dict]) -> list[PlannedInstance]:
        planner = Planner(
            num_instances=self.config.num_instances,
            categories=self.config.categories,
            seed=self.config.seed,
            max_per_module=self.config.max_targets_per_module,
        )
        plan = planner.plan(targets)
        print(f"[plan] {len(plan)} instances across {len(self.config.categories)} categories")
        return plan

    def _generate_one(
        self,
        container: Container,
        prompt_builder: PromptBuilder,
        planned: PlannedInstance,
        generated_ids: list[str],
    ) -> InstanceRecord:
        config = self.config
        record = InstanceRecord(
            instance_id=planned.instance_id,
            category=planned.category,
            target_file=planned.target["file"],
            target_qualname=planned.target["qualname"],
            status="planned",
            started_at=_now(),
        )
        instance_log_dir = self.logs_dir / planned.instance_id
        instance_log_dir.mkdir(parents=True, exist_ok=True)

        # 1. Stage the prompt (fresh session; only this prompt carries context).
        prompt = prompt_builder.build(planned, generated_ids)
        (instance_log_dir / "prompt.md").write_text(prompt, encoding="utf-8")
        prompt_container_path = f"/tmp/repogen/prompt_{planned.instance_id}.md"
        container.cp_to(instance_log_dir / "prompt.md", prompt_container_path)

        # 2. One isolated agent session for this single instance.
        assert self.backend is not None
        agent_result = self.backend.run_task(
            container=container,
            prompt_container_path=prompt_container_path,
            workspace=config.workdir,
            host_log_dir=instance_log_dir,
            tag=planned.instance_id,
            timeout_s=config.agent_timeout_s,
        )
        if not agent_result.ok:
            record.status = "agent_failed"
            record.note = agent_result.note or f"agent exit={agent_result.exit_code}"

        # 3. Collect whatever the agent produced (even on failure, for debugging).
        container_instance_dir = f"{config.container_qa_dir}/{planned.instance_id}"
        host_instance_dir = self.instances_dir / planned.instance_id
        copied = False
        if container.path_exists(container_instance_dir):
            copied = container.cp_from(f"{container_instance_dir}/.", host_instance_dir)
        logs_path = f"{config.workdir}/logs/{config.qa_dir_name}/{planned.instance_id}"
        if container.path_exists(logs_path):
            container.cp_from(f"{logs_path}/.", instance_log_dir / "harvest")

        # 4. Light existence check (validation gates are a later stage by design).
        if record.status != "agent_failed":
            oracle = host_instance_dir / "oracle.json"
            if copied and oracle.exists() and oracle.stat().st_size > 0:
                record.status = "generated"
            else:
                record.status = "no_oracle"
                record.note = "instance dir or oracle.json missing after agent run"

        record.finished_at = _now()
        return record

    # -- persistence -------------------------------------------------------

    def _save_config(self) -> None:
        data = {
            key: (str(value) if isinstance(value, Path) else value)
            for key, value in asdict(self.config).items()
        }
        with (self.run_dir / "run_config.json").open("w", encoding="utf-8") as f:
            json.dump(data, f, indent=2, default=str)
            f.write("\n")

    def _save_plan(self, plan: list[PlannedInstance]) -> None:
        with (self.run_dir / "plan.json").open("w", encoding="utf-8") as f:
            json.dump([p.as_dict() for p in plan], f, indent=2)
            f.write("\n")

    @staticmethod
    def _load_targets(path: Path) -> list[dict]:
        with Path(path).open("r", encoding="utf-8") as f:
            data = json.load(f)
        return data["targets"] if isinstance(data, dict) else data


def _now() -> str:
    return _dt.datetime.now().isoformat(timespec="seconds")
